{% set name = "bibtexparser" %}
{% set version = "1.3.0" %}
{% set sha256 = "971a0840700f5282d61b8c119cd4e208b8e546a91f9043ead4e440734fbf9f5e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/b/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pyparsing >=2.0.3
    - python >=3.6
    - setuptools
  run:
    - pyparsing >=2.0.3
    - python >=3.6

test:
  imports: bibtexparser

about:
  home: https://bibtexparser.readthedocs.org/
  license: LGPL-3.0-only OR BSD-3-Clause
  license_file: COPYING
  summary: A module for parsing BibTeX files.

extra:
  recipe-maintainers:
    - pkgw
