{% set name = "bibtexparser" %}
{% set version = "1.4.1" %}
{% set sha256 = "e00e29e24676c4808e0b4333b37bb55cca9cbb7871a56f63058509281588d789" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/b/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pyparsing >=2.0.3
    - python >=3.6
    - setuptools
  run:
    - pyparsing >=2.0.3
    - python >=3.6

test:
  imports: bibtexparser

about:
  home: https://bibtexparser.readthedocs.org/
  license: LGPL-3.0-only OR BSD-3-Clause
  license_file: COPYING
  summary: A module for parsing BibTeX files.

extra:
  recipe-maintainers:
    - pkgw
