{% set name = "bibtexparser" %}
{% set version = "1.4.2" %}
{% set sha256 = "dd5d54a1ec6d27b6485ce2f6b9aa514b183fb2b8d4bf5f19333a906eedaf8eaa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/b/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pyparsing >=2.0.3
    - python {{ python_min }}
    - setuptools
  run:
    - pyparsing >=2.0.3
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports: bibtexparser

about:
  home: https://bibtexparser.readthedocs.org/
  license: LGPL-3.0-only OR BSD-3-Clause
  license_file: COPYING
  summary: A module for parsing BibTeX files.

extra:
  recipe-maintainers:
    - pkgw
