{% set name = "bibtexparser" %}
{% set version = "1.1.0" %}
{% set sha256 = "df8966ea752db6d74657a69b9d684a61aa33457ad6d9d50e41c50ef7f374907f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/b/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script:
    - python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - future >=0.16
    - pyparsing >=2.0.3
    - python
    - setuptools
  run:
    - future >=0.16
    - pyparsing >=2.0.3
    - python

test:
  imports:
    bibtexparser

about:
  home: https://bibtexparser.readthedocs.org/
  license: LGPLv3 or BSD
  # license_file: COPYING -- file not included in the current distribution
  summary: 'A module for parsing BibTeX files.'

extra:
  recipe-maintainers:
    - pkgw
