travis:
  secure:
    BINSTAR_TOKEN: f59e7Bvlw4dG4YknEexzdfEFZDmG4y9vXjHRRpLzqLS91hxY46rFxrgvXRb6DLOPyvvLkjMXONoq4o2BW0dJf8j5057XZPcnZxOccHrLtV987MZEFOreW4XvmjklNf8T4TCXZEEShFL6cJ+Fq801t2oWD3fIBx9zOfP4P9a1gnLwc0+3EvF9VuZp7wphCTElIdrtFwRshjl4h1naAQKTPDdlXFu5Pa64j9lz/bm4sPxG0EBIQ3CVFlmOP1IDODMdpPMmdd+bpTTGp5+yii7dPXDGeFyCxCZQUJsH6MHsky9IGMMlDLFiSXZ+esUy9QN8M+CIjsbbH/jydK4YoFRHaJvoHhcW9Ut3vrGObZIll/ZxvW7mAUHXTbX1B5MFEGYiMf1Q8mb01HLXwIyV7jIXMVMV0LCVdmeMyNSy/C6jF42AKDur/oBmdjRwXK0OnjnAsNWQkfJQgy77aQNQEeIRc3u/pXocTGa19YcXFNhlmtynRZJSz/NAXniS7n+xS8vbfxafo1915egSgxG8xT4oxbDMXKBRFHLiGb74GLywY0kZ7oa/gVafNZWwApkoG+uN9T7CJq0TTxb+U2JhPlo0jWodfAvJj/lpKX7Ww3+xsRKekgj4YXHT6khGOIALlBZZtIdxBa2F5uvLsZ0Mq0BPilDnuTbrh0r1oBtXpEcXxI8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
