travis:
  secure:
    BINSTAR_TOKEN: ChqgOEt026WGjqwZzJkxbOqYBivrVz1vs28WRyIMxflER5+UqzB8aV8n6XBwPPxUHqC1Doh3/BRmRRPM/RW45EZ8omGwqGZ4sVPC94lvEM0Mo7QYg6VsVcqgu0SpCUZBHtLe9fwJLXMY9csD/vblrh6f1Ju1laSx8UJTSKacPO2WzlJpjkBDUHcpYYLQzsqdFFkAvCvwFMJd8X2woNCapCvE17wIQDVPC1LDyKw6QE+S1iarOifr0202105cIfGJWFOQ/zddmWVk8eTJbL/5aUInPMOU3hQm8503iNbRDlNXvVoMUi+rvKkKeJnAi85S4z/9yvUtf8kk50up7BXTJckkPtxnfHbHsrC1XKNZmatIKsU4f0G7j6rQwMwQZewMWaF2febKtwWhXHcKnuT2NF3SZEf9EiR3BPDxSFfBSAgK80ebueC1im0+Lqw4wzOfXtoZilGs9XbxHMDPbcHqHlAsrG+cYnINb00ykB3idCHEQ4EkuDaR0PQ111yIuzfgKf3Th9J4dba7OdQzB9wW5dh4O7bcD0poen93Xv/0YQjClCFP8fjpdsD6Jbs7IwgWfCO8e2DnqEafzkGqWfFS5jW7yINdSui1PUuZuy5FFLq5h2SJmy5da38hRgNM3+tbmilYem0s58AzYzcKeVZ+DavvT34gvkoL45gLF6UZxL8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
